### PR TITLE
Add forth exercise

### PR DESCRIPTION
**Pull request by ricemery**
Add forth exercise

### CODE REVIEW

**Comment by ricemery** [comment]
@kytrinyx - question for you. The Travis CI build is failing on my pull request. The problem is that in the src/main/scala directory I have a .scala file that needs to be filled out by the user. The file contains a couple of class definitions that define the interface needed by the unit tests.

In the root is the example.scala file that has a "real" solution. The build.sbt is written to compile the file in src/main/scala, since this is what the user will want. The example.scala is ignored by build.sbt. 

Travis CI is trying to compile and run the unit tests, which will fail since the example.scala is ignored. 

Any suggestions on how to deal with this case?  I could add Ignore flags on all the unit tests. I'm not sure if there is a better way.

Thanks

**Comment by kytrinyx** [comment]
Is there a a way to make the build ignore the stub file when running the tests against examlpe.scala?

**Comment by ricemery** [comment]
@kytrinyx - I was making this harder than I needed to. I changed the stub to include traits instead. So, now the user will have a couple of traits to implement. And, the CI build should pass.

Thanks

**Comment by kytrinyx** [comment]
That sounds good.

**Pull request closed without merging**
