### PR TITLE
Add hints to hello-world exercise

### PR DESCRIPTION
**Pull request by abo64**
#220 add `HINTS.md` to `hello-world` exercise.
Question is whether we should agree on a common format for those hints?

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
I love this. The only thing I'm not sure of, is the link for the no-null hint. It now links to Wikipedia, but I think a Scala-specific link would be better. I've managed to find [this explanation](https://tpolecat.github.io/2014/05/09/return.html), which does are fairly good job of explaning *why* you shouldn't use `return`. It might be a bit difficult for newbies though.

**Comment by abo64** [comment]
@ErikSchierboom I was also not too happy about this link, but couldn't find anything nice (incl. your link which I also considered too theoretical for beginners).
Now I just searched again and stumbled upon [this](http://stackoverflow.com/questions/24856106/return-in-a-scala-function-literal). What do you think?

**Comment by ErikSchierboom** [comment]
Much better. I think it is at least good enough until we find something better.

**Comment by abo64** [comment]
changed the link.

**Comment by abo64** [comment]
@ErikSchierboom Seems it cannot handle these ordered lists.
Changed it to an unordered list (using hyphens).

**Comment by ErikSchierboom** [comment]
Looks good. 

@ricemery would you like to merge the PR's yourselves, or should we (the other maintainers) also be allowed to do that? Perhaps we should make it a rul that we cannot merge our own PR's, to prevent overlooking mistakes.

**Comment by abo64** [comment]
I found [this](https://github.com/exercism/x-common/blob/master/CONTRIBUTING.md#maintaining-a-track) quite plausible. But:
*Avoid merging your own pull requests (but it's fine if it's really simple)* - the question is always what is "simple".

**Comment by ErikSchierboom** [comment]
Indeed. But now that we have several maintainers, I think we could try to not merge our own PR's. But I don't know what the others thing about this.

**Comment by abo64** [comment]
Most often the rules without any exceptions are the best.
So I also think we should try to never merge our own PRs.

**Comment by ricemery** [comment]
Agreed. By default we should not merge our own PRs.

**Comment by ErikSchierboom** [comment]
@ricemery So it would be okay if I merged this PR?

**Comment by ricemery** [comment]
Absolutely!

Thanks

**Comment by ErikSchierboom** [comment]
Thanks @abo64!

**Pull request merged**
