### PR TITLE
Add hints to leap exercise

### PR DESCRIPTION
**Pull request by abo64**
#220

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
I wonder if people will understand the "single Boolean expression" bit. Perhaps we could link to an example?

**Comment by abo64** [comment]
Best link I could find is [this one](http://cs.wellesley.edu/~cs111/spring00/lectures/boolean-simplification.html). Unfortunately it is in Java, but might still be OK?

**Comment by ricemery** [comment]
I think it would be fine to include the link.

**Comment by ErikSchierboom** [comment]
Agreed, I think it's a good hint.

**Comment by abo64** [comment]
Added the link.

**Comment by ErikSchierboom** [comment]
I think this looks fine. Merged.

**Pull request merged**
