### PR TITLE
meetup: Switch to java.time library

### PR DESCRIPTION
**Pull request by abo64**
#275 Switch to java.time library
#235 Upgrade to Scala 2.12
#125 Add topics to `config.json`

### CODE REVIEW

**Comment by abo64** [comment]
@ricemery @ErikSchierboom Seems it couldn't download `sbt`.
What is a good course of action here? Just retry? How?

**Comment by ricemery** [comment]
http://stackoverflow.com/questions/17606874/trigger-a-travis-ci-rebuild-without-pushing-a-commit indicates that there should be a rebuild button on the Travis CI Page. But, I don't see the button even if I am logged in. 

So... I think the solution is to probably cancel this pull request and resubmit a new pull request.

**Comment by abo64** [comment]
@ricemery I tried Close&Re-open the PR as described in that link. Seems to have worked. Thanks!

**Comment by ricemery** [comment]
thanks @abo64

**Pull request merged**
