### PR TITLE
Add hints to roman-numerals exercise

### PR DESCRIPTION
**Pull request by abo64**
#220 
Perhaps the first hint about `Seq` or `SortedMap` is too much of a spoiler already?

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
It is a bit of a spoiler. Do people in general struggle with this exercise? Do they come up with `Seq` or `SortedMap` themselves?

**Comment by abo64** [comment]
Some just use a `Map` or some other unsorted data structure. But maybe you are right, shall I remove this line?

**Comment by ErikSchierboom** [comment]
@abo64 It can wait till monday :)

**Comment by abo64** [comment]
thx @ErikSchierboom 
I removed that spoiler.

**Comment by ErikSchierboom** [comment]
Great, thanks!

**Pull request merged**
