### PR TITLE
Add pending keyword to tests

### PR DESCRIPTION
**Pull request by ErikSchierboom**
This PR should fix the remaining open items in #133.

### CODE REVIEW

**Comment by ricemery** [comment]
@ErikSchierboom , did my merging the rename pull first screw up this pull request?

**Comment by ErikSchierboom** [comment]
@ricemery Probably. I'll do a rebase tonight.

**Comment by ricemery** [comment]
Sorry about that! This is the second time I have merged your changes out of
order. I'll hang my head in shame for the day!

**Comment by ErikSchierboom** [comment]
@ricemery No problem. I've rebased and update the PR.

**Pull request merged**
