### PR TITLE
Add book-store exercise

### PR DESCRIPTION
**Pull request by ricemery**
Add book-store exercise

### CODE REVIEW

**Comment by abo64** [comment]
@ricemery You have my approval, too. So you can just merge.

One remark:
The `targetgrouping` information in [canonical-data.json](https://github.com/exercism/x-common/blob/master/exercises/book-store/canonical-data.json) is ignored.
One could soup up the exercise by letting `total` return a pair consisting of the total price and the grouping.

**Comment by ricemery** [comment]
@abo64 , @ErikSchierboom  - thanks.

@abo64  - Neither the Java or C# impls use the `targetgrouping` either. Maybe @ErikSchierboom knows why? :)

**Comment by ErikSchierboom** [comment]
Well, I think that's because the exercise's README states the following:

> Your mission is to write a piece of code to calculate the price of any conceivable shopping basket (containing only books of the same series), giving as big a discount as possible.

In general, I'd like exercises to only have a single goal, and I think calculating the target price is the correct one here. I assume the target grouping is just there to help people understand the solution.

**Comment by ricemery** [comment]
Excellent points. Thanks

**Pull request merged**
