### PR TITLE
Move exercises to subdirectory. Fixes #97

### LINKED ISSUE #97: Move exercises to subdirectory
The problems api (x-api) now supports having exercises collected in a subdirectory
named `exercises`.

That is to say that instead of having a mix of `bin`, `docs`, and individual exercises,
we can have `bin`, `docs`, and `exercises` in the root of the repository, and all
the exercises collected in a subdirectory.

In other words, instead of this:

```
x{TRACK_ID}/
├── LICENSE
├── README.md
├── bin
│   └── fetch-configlet
├── bowling
│   ├── bowling_test.ext
│   └── example.ext
├── clock
│   ├── clock_test.ext
│   └── example.ext
├── config.json
└── docs
│   ├── ABOUT.md
│   └── img
... etc
```

we can have something like this:

```
x{TRACK_ID}/
├── LICENSE
├── README.md
├── bin
│   └── fetch-configlet
├── config.json
├── docs
│   ├── ABOUT.md
│   └── img
├── exercises
│   ├── bowling
│   │   ├── bowling_test.ext
│   │   └── example.ext
│   └── clock
│       ├── clock_test.ext
│       └── example.ext
... etc
```

This has already been deployed to production, so it's safe to make this change whenever you have time.

### PR DESCRIPTION
**Pull request by ricemery**
Move exercises to subdirectory. Fixes #97

### CODE REVIEW

**Comment by kytrinyx** [comment]
When I run configlet against this locally I get:

```
$ configlet .
Evaluating .
-> No directory found for [queen-attack].
```

Did it get lost in the shuffle?

**Comment by kytrinyx** [comment]
Oh:

```plain
$ find . -name queen-attack
./exercises/etl/queen-attack
```

**Comment by ricemery** [comment]
Oops. I will close this one. And, resubmit.

**Comment by kytrinyx** [comment]
Not sure anyone ever mentioned, but you can `git push -f origin yourbranch` to update a PR with a new history. It's really handy for cases like this.

**Pull request closed without merging**
